"""criação das tabelas 

Revision ID: 582b19b1a917
Revises: 
Create Date: 2025-11-10 23:32:24.399553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '582b19b1a917'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material',
    sa.Column('id_material', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('autor', sa.String(length=150), nullable=True),
    sa.Column('isbn', sa.String(length=20), nullable=True),
    sa.Column('editora', sa.String(length=100), nullable=True),
    sa.Column('ano_publicacao', sa.Integer(), nullable=True),
    sa.Column('tipo_material', sa.Enum('livro_fisico', 'ebook', 'periodico', 'outro', name='tipomaterial'), nullable=False),
    sa.Column('formato_arquivo', sa.String(length=10), nullable=True),
    sa.Column('numero_paginas', sa.Integer(), nullable=True),
    sa.Column('idioma', sa.String(length=50), nullable=True),
    sa.Column('area_conhecimento', sa.String(length=100), nullable=True),
    sa.Column('palavras_chave', sa.Text(), nullable=True),
    sa.Column('quantidade_total', sa.Integer(), nullable=True),
    sa.Column('quantidade_disponivel', sa.Integer(), nullable=True),
    sa.Column('url_arquivo', sa.String(length=255), nullable=True),
    sa.Column('data_cadastro', sa.Date(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_material'),
    sa.UniqueConstraint('isbn')
    )
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('matricula', sa.String(length=50), nullable=False),
    sa.Column('tipo_usuario', sa.Enum('aluno', 'docente', 'colaborador', 'administrador', name='tipousuario'), nullable=False),
    sa.Column('turma', sa.String(length=50), nullable=True),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('data_cadastro', sa.Date(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('matricula')
    )
    op.create_table('emprestimo',
    sa.Column('id_emprestimo', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_material', sa.Integer(), nullable=False),
    sa.Column('data_emprestimo', sa.Date(), nullable=False),
    sa.Column('data_prevista_devolucao', sa.Date(), nullable=False),
    sa.Column('data_devolucao', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ativo', 'devolvido', 'atrasado', name='statusemprestimo'), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_material'], ['material.id_material'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_emprestimo')
    )
    op.create_table('logs_acesso',
    sa.Column('id_log', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('acao', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_log')
    )
    op.create_table('reserva',
    sa.Column('id_reserva', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_material', sa.Integer(), nullable=False),
    sa.Column('data_reserva', sa.Date(), nullable=False),
    sa.Column('data_expiracao', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ativa', 'cancelada', 'concluida', 'expirada', name='statusreserva'), nullable=True),
    sa.ForeignKeyConstraint(['id_material'], ['material.id_material'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_reserva')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reserva')
    op.drop_table('logs_acesso')
    op.drop_table('emprestimo')
    op.drop_table('usuario')
    op.drop_table('material')
    # ### end Alembic commands ###
